# ansible-playbook -i hosts.yml 008a-huawei_olt_config_service_port.yml
- name: EXCEED VLAN MOVE 
  hosts: huawei_olt
  connection: local
  gather_facts: no
  vars:
    # designated_vlan: '3002'
    # target_gemindex: '3'
    vlan_max_subs: 17
    # subscriber_to_move: 8

  tasks:
    - name: Get all available vlan 
      multipolar_huawei_olt_command_display_anything:
        olt_display_command: 'display vlan all'
        ansible_host: '{{ hostvars[inventory_hostname].ansible_host }}'
        ansible_network_os: '{{ hostvars[inventory_hostname].ansible_network_os }}'
        ansible_platform: '{{ hostvars[inventory_hostname].ansible_platform }}'
        ansible_user: '{{ hostvars[inventory_hostname].ansible_user }}'
        ansible_ssh_pass: '{{ hostvars[inventory_hostname].ansible_ssh_pass }}'
      register: all_vlan
    
    - name: Get exceed vlan (subs more than {{ vlan_max_subs }})
      set_fact:
        exceed_vlan: '{{item.vlan}}'
      when: item.servportnum >= "{{vlan_max_subs}}"
      with_items: "{{all_vlan.return_from_devices}}"

    - name: Show vlan with member than  {{vlan_max_subs}}
      debug:
        msg: 'exceeded vlan is => {{ exceed_vlan }}'
      
    - name: Get all service port that use vlan {{exceed_vlan}}
      multipolar_huawei_olt_command_display_service_port:
        service_port_vlan: '{{exceed_vlan}}'
        ansible_host: '{{ hostvars[inventory_hostname].ansible_host }}'
        ansible_network_os: '{{ hostvars[inventory_hostname].ansible_network_os }}'
        ansible_platform: '{{ hostvars[inventory_hostname].ansible_platform }}'
        ansible_user: '{{ hostvars[inventory_hostname].ansible_user }}'
        ansible_ssh_pass: '{{ hostvars[inventory_hostname].ansible_ssh_pass }}'
      register: service_port

    - name: Undo existing service-port and push new service-port with new VLAN - {{designated_vlan}}
      multipolar_huawei_olt_config_service_port:
        command_undo: 'undo service-port {{item.index}}'
        command_set: 'service-port {{item.index}} vlan {{ designated_vlan }} gpon  {{item.frameslot}}{{item.port}} ont {{item.vpi}} gemport {{target_gemindex}} multi-service user-vlan {{item.flowpara}} tag-transform translate inbound traffic-table index {{item.tx}} outbound traffic-table index {{item.rx}}'
        ansible_host: '{{ hostvars[inventory_hostname].ansible_host }}'
        ansible_network_os: '{{ hostvars[inventory_hostname].ansible_network_os }}'
        ansible_platform: '{{ hostvars[inventory_hostname].ansible_platform }}'
        ansible_user: '{{ hostvars[inventory_hostname].ansible_user }}'
        ansible_ssh_pass: '{{ hostvars[inventory_hostname].ansible_ssh_pass }}'
      loop_control:
        label: " Moving SERVICEPORT-INDEX {{ item.index }} from VLAN -{{ item.vlanid }} gemindex-{{item.vci}} into VLAN -{{designated_vlan}} gemindex-{{target_gemindex}}"
      # 9 means count of olt that want to move to new vlan
      with_items: '{{ service_port.return_from_devices[:9] }}'